[WIP] feat/[sfa-16]: add token and currency types and update search collection
nftfy/nftfy-amm pull request #18
Opened 2023-01-11 19:44 UTC by freitasgouvea

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2023-01-17 18:23 UTC, luanpontolio reviewed
The PR has a WIP in the name.

There are some comments and `console.logs` do you think it is better to maintain this?

2023-01-17 18:28 UTC, luanpontolio commented on apps/web/src/components/SearchModal/CommonBases.tsx
> +          const factoryContract = getIUniswapV2FactoryContract(FACTORY_ADDRESS[chainId], data )
Maybe we can create a hook useFactoryContract(). What do you think?

2023-01-17 18:28 UTC, luanpontolio commented on apps/web/src/components/SeeNftsModal/SeeNftsModal.tsx
> +      <img src={collectionImage ?? 'https://testnets.opensea.io/static/images/placeholder.png'} alt="" />
Maybe it is better to add the `placeholder.png`  in our project

2023-01-17 21:03 UTC, arthurmr96 requested changes

2023-01-17 21:03 UTC, arthurmr96 commented on apps/web/src/components/SeeNftsModal/SeeNftsModal.tsx
> +      </Action> */}
Remove the comment if it's not necessary anymore

2023-01-18 18:32 UTC, arthurmr96 approved these changes

2023-01-19 18:20 UTC, merged