Sfa 29 add liquidity token nft
nftfy/nftfy-amm pull request #21
Opened 2023-01-20 18:53 UTC by luanpontolio

2023-01-20 19:37 UTC, arthurmr96 requested changes

2023-01-20 19:37 UTC, arthurmr96 commented on apps/web/src/views/AddLiquidity/index.tsx
> +        const isNft = currentNft === Field.CURRENCY_A
It’s not possible to B be a NFT?

2023-01-23 13:09 UTC, luanpontolio commented on apps/web/src/views/AddLiquidity/index.tsx
> +        const isNft = currentNft === Field.CURRENCY_A
Only one of the inputs can be an NFT. I'll check if this is happening!

2023-01-23 13:39 UTC, arthurmr96 approved these changes

2023-01-23 13:39 UTC, merged