feat: Verify pool of a collection exist
nftfy/nftfy-amm pull request #26
Opened 2023-01-25 22:28 UTC by luanpontolio

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2023-01-27 13:36 UTC, arthurmr96 requested changes

2023-01-27 13:36 UTC, arthurmr96 commented on apps/web/src/hooks/useContract.ts
> +  return useContract<Erc20 | Erc721collection>(tokenAddress, abi || ERC20_ABI, withSignerIfPossible)
Is it not better to change the ERC20 ABI for the Wrapped NFT? To make available the collection property also when the desired address is a WNFT

2023-01-27 15:09 UTC, arthurmr96 requested changes

2023-01-27 15:09 UTC, arthurmr96 commented on apps/web/src/hooks/usePairs.ts
> +          return tokenA && tokenB && !tokenA.equals(tokenB) ? computePairAddress({ factoryAddress: FACTORY_ADDRESS[chainId], tokenA, tokenB }) : undefined
`computePairAddress` does the same thing the `getAddress` did but with the correct factory?

2023-01-27 15:09 UTC, arthurmr96 commented on apps/web/src/state/user/hooks/useUserAddedTokens.ts
> +export default function useUserAddedTokens(): Token[] | WrappedNftErc20Token[] {
```suggestion
export default function useUserAddedTokens(): WrappedNftErc20Token[] {
```

2023-01-27 15:09 UTC, arthurmr96 commented on apps/web/src/state/user/hooks/useUserAddedTokens.ts
> +export default function useUserAddedTokens(): Token[] | WrappedNftErc20Token[] {
`WrappedNftErc20Token` already extends `Token`

2023-01-27 15:09 UTC, arthurmr96 commented on apps/web/src/state/wallet/hooks.ts
> +    () => tokens?.filter((t?: Token | WrappedNftErc20Token): t is Token | WrappedNftErc20Token => isAddress(('collection' in t && t?.collection) || t?.address) !== false) ?? [],
`WrappedNftErc20Token` already extends `Token`

2023-01-27 15:16 UTC, luanpontolio commented on apps/web/src/hooks/usePairs.ts
> +          return tokenA && tokenB && !tokenA.equals(tokenB) ? computePairAddress({ factoryAddress: FACTORY_ADDRESS[chainId], tokenA, tokenB }) : undefined
The `Pair.getAddress` is a method used by pancake-swap to find the LP token for the pair. 
In the SDK the wrong address was used for `FACTORY` and `INIT_CODE_HASH.`

2023-01-27 15:18 UTC, luanpontolio commented on apps/web/src/hooks/useContract.ts
> +  return useContract<Erc20 | Erc721collection>(tokenAddress, abi || ERC20_ABI, withSignerIfPossible)
Ok. Maybe we can change WrappedNft to Erc20Wrapped. What do you think?

2023-01-27 15:52 UTC, arthurmr96 commented on apps/web/src/hooks/usePairs.ts
> +          return tokenA && tokenB && !tokenA.equals(tokenB) ? computePairAddress({ factoryAddress: FACTORY_ADDRESS[chainId], tokenA, tokenB }) : undefined
but all that it was being done on the method, is being doing by the new method with the correct addresses?

2023-01-27 18:02 UTC, arthurmr96 approved these changes

2023-01-30 18:31 UTC, arthurmr96 approved these changes

2023-01-31 19:54 UTC, merged