feat/[SFA-78]: add select nfts modal
nftfy/nftfy-amm pull request #27
Opened 2023-01-27 02:39 UTC by freitasgouvea

2023-01-27 17:57 UTC, arthurmr96 requested changes

2023-01-27 17:57 UTC, arthurmr96 commented on apps/web/src/components/SeeNftsModal/SeeNftsRemoveLiquidityModal.tsx
> +  const collectionName = items[0].token.collection.name || ''
```suggestion
  const collectionName = items[0].token.collection.name || 'UNKNOWN'
```

2023-01-27 17:57 UTC, arthurmr96 commented on apps/web/src/components/SeeNftsModal/SeeNftsRemoveLiquidityModal.tsx
> +  const collectionName = items[0].token.collection.name || ''
Suggestion to follow the pattern that the fork use for when you can't obtain the collection name

2023-01-27 19:00 UTC, luanpontolio approved these changes

2023-01-30 20:01 UTC, arthurmr96 approved these changes

2023-02-01 15:05 UTC, merged