feat: Adjust SwapForm to avoid infinite loop
nftfy/nftfy-amm pull request #34
Opened 2023-02-06 21:16 UTC by luanpontolio

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2023-02-07 20:02 UTC, arthurmr96 requested changes

2023-02-07 20:02 UTC, arthurmr96 commented on apps/web/src/hooks/Tokens.ts
> +    wrappedTokenAddress[0] || NO_WRAPPED_NFT_CONTRACT,
I think you may need to get the `.result` property from this position

2023-02-07 20:08 UTC, luanpontolio commented on apps/web/src/hooks/Tokens.ts
> +    wrappedTokenAddress[0] || NO_WRAPPED_NFT_CONTRACT,
No, because I already return the `result` for wrappedTokenAddress. 

Take a look at line 294:

https://github.com/nftfy/nftfy-amm/pull/34/files/ecfc6d9616807c43d957c05d7b1b37762e7367e5#diff-426c0560f4bc48681915c2013e8c05bc226487e39b20b54926b5f90dc8b583f7R294

2023-02-07 20:11 UTC, arthurmr96 approved these changes

2023-02-08 13:37 UTC, freitasgouvea approved these changes

2023-02-08 14:42 UTC, merged