feat: add getNftPoolBalance
nftfy/nftfy-amm pull request #35
Opened 2023-02-09 01:05 UTC by freitasgouvea

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2023-02-09 19:05 UTC, arthurmr96 requested changes

2023-02-09 19:05 UTC, arthurmr96 commented on apps/web/src/components/SeeNftsModal/SeeNftsWalletModal.tsx
> +      if (list.length === maxItems) {
```suggestion
      if (list?.length === maxItems) {
```

2023-02-09 19:20 UTC, arthurmr96 approved these changes

2023-02-10 13:28 UTC, luanpontolio approved these changes

2023-02-10 13:29 UTC, merged