Feature/[SFA-145]: update settings modal and increase slippage tolerance
nftfy/nftfy-amm pull request #39
Opened 2023-02-14 00:04 UTC by freitasgouvea

[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-frontend/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does

2023-02-14 14:04 UTC, arthurmr96 requested changes

2023-02-14 14:04 UTC, arthurmr96 commented on apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
> +        )} */}
You can remove this commented code, if we want in the future to get it back we can consult the git history

2023-02-14 14:04 UTC, arthurmr96 commented on apps/web/src/components/Menu/GlobalSettings/SettingsModal.tsx
> +            </Flex> */}
You can remove this commented code, if we want in the future to get it back we can consult the git history

2023-02-14 19:36 UTC, luanpontolio approved these changes

2023-02-14 19:36 UTC, luanpontolio commented on apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
> +              setUserSlippageTolerance(2000)
Could it be a constant or an Env.?

2023-02-15 18:21 UTC, freitasgouvea commented on apps/web/src/components/Menu/GlobalSettings/TransactionSettings.tsx
> +              setUserSlippageTolerance(2000)
Yes, of course, we could put it in the env or be a constant too, but I think that in this case is just the percentage that will appear on the button and it's only used here, so maybe it's better to keep it the same as the original project. Anyway, thanks @luanpontolio for the suggestion and we can improve these things in the next implementations

2023-02-15 18:21 UTC, merged